name: anything_hub
description: "Un hub modular agéntico y web para Android."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  path: ^1.9.0
  uuid: ^4.4.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.5
  http: ^1.2.2
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/images/
    - assets/mylogo.png

flutter_launcher_icons:
  image_path: "assets/mylogo.png"
  android: true
  ios: false
  image_path_android: "assets/mylogo.png"
