name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # O puedes usar 'stable' para la última versión disponible
          channel: 'stable'
          cache: true

      - name: Ensure Android Native Structure Exists
        run: |
          if [ ! -d "android" ]; then
            flutter create . --project-name anything_hub --org com.anything.hub --platforms=android
          fi

      - name: Set Gradle Version to 9.3.1 (Required by AGP)
        run: |
          PROP_FILE="android/gradle/wrapper/gradle-wrapper.properties"
          if [ -f "$PROP_FILE" ]; then
            sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-9.3.1-bin.zip|g' "$PROP_FILE"
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
